### PR TITLE
Remove unused code from stdom.py

### LINKED ISSUE #3: Get unit test coverage to 100%
And pin it there via `setup.cfg`.

### PR DESCRIPTION
**Pull request by jamadden**
Fixes #3.

### CODE REVIEW

**Review by icemac — APPROVED** [review]
Cool, I especially like the `raise NotImplementedError()` as it is way better than getting an `AttributeError` because the method got deleted.

**Comment by jamadden** [comment]
Sweet, thanks. Can we get a PyPI release when convenient, please?

**Comment by icemac** [comment]
@jamadden I added you as owner of this package on PyPI.

**Comment by jamadden** [comment]
Thanks! 4.2.0 has been released.

**Pull request merged**
